### LIBRARY

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
%matplotlib inline

In [3]:
df = pd.read_csv("../DATA/DATA.csv",  encoding='ISO-8859-1')

In [4]:
df.head()

,date.time,Inside Temp,High Inside Temp,Low Inside Temp,Inside Hum,High Inside Hum,Low Inside Hum,Inside Dew Point - °C,Inside Heat Index,Barometer,...,Low Hum .1,Dew Point .1,High Dew Point,Low Dew Point .1,Wet Bulb .1,High Wet Bulb .1,Low Wet Bulb .1,Heat Index .1,High Heat Index,Unnamed: 71
0,2/24/2024 10:45,23.9,23.9,23.8,60.5,60.5,57.3,15.8,24.3,1019.7,...,57.1,57.1,18.8,18.8,18.8,20.9,20.9,20.9,29.2,29.2
1,2/24/2024 10:50,24.2,24.3,24.0,62.7,62.7,60.7,16.6,24.6,1019.6,...,57.1,57.1,18.8,18.8,18.8,20.9,20.9,20.9,29.2,29.2
2,2/24/2024 10:55,24.4,24.4,24.2,64.3,64.5,63.4,17.3,25.0,1019.6,...,57.1,57.1,18.8,18.8,18.8,20.9,20.9,20.9,29.2,29.2
3,2/24/2024 11:00,24.7,24.7,24.4,64.8,65.0,64.5,17.6,25.3,1019.5,...,60.4,57.0,18.8,18.9,18.6,20.8,21.0,20.7,28.1,29.3
4,2/24/2024 11:05,24.9,24.9,24.7,64.9,64.9,64.6,17.8,25.6,1019.5,...,60.4,57.0,18.8,18.9,18.6,20.8,21.0,20.7,28.1,29.3

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47839 entries, 0 to 47838
Data columns (total 72 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date.time                  47839 non-null  object
 1   Inside Temp                47839 non-null  float64
 2   High Inside Temp           47839 non-null  float64
 3   Low Inside Temp            47839 non-null  float64
 4   Inside Hum                 47839 non-null  float64
 5   High Inside Hum            47839 non-null  float64
 6   Low Inside Hum             47839 non-null  float64
 7   Inside Dew Point - °C      47839 non-null  float64
 8   Inside Heat Index          47839 non-null  float64
 9   Barometer                  47839 non-null  float64
 10  High Bar                   47839 non-null  float64
 11  Low Bar                    47839 non-null  float64
 12  Absolute Pressure          47839 non-null  float64
 13  Temp                       47839 non-null  object
 14  High Temp                  47839 non-null  object
 15  Low Temp                   47839 non-null  object
 16  Hum                        47839 non-null  object
 17  High Hum                   47839 non-null  object
 18  Low Hum                    47839 non-null  object
 19  Dew Point                  47839 non-null  object
 20  High Dew Point             47839 non-null  object
 21  Low Dew Point              47839 non-null  object
 22  Wet Bulb                   47839 non-null  object
 23  High Wet Bulb              47839 non-null  object
 24  Low Wet Bulb               47839 non-null  object
 25  Avg Wind Speed             47839 non-null  object
 26  Prevailing Wind Direction  47749 non-null  object
 27  High Wind Speed            47839 non-null  object
 28  High Wind Direction        47797 non-null  object
 29  Wind Chill                 47839 non-null  object
 30  Low Wind Chill             47839 non-null  object
 31  Heat Index                 47839 non-null  object
 32  High Heat Index            47839 non-null  object
 33  THW Index                  47839 non-null  object
 34  High THW Index             47839 non-null  object
 35  Low THW Index              47839 non-null  object
 36  Wind Run                   47839 non-null  object
 37  THSW Index                 47839 non-null  object
 38  High THSW Index            47839 non-null  object
 39  Low THSW Index             47839 non-null  object
 40  Rain                       47839 non-null  float64
 41  High Rain Rate             47839 non-null  object
 42  Solar Rad                  47839 non-null  object
 43  High Solar Rad             47839 non-null  object
 44  UV Index                   47839 non-null  object
 45  High UV Index              47839 non-null  object
 46  UV Dose                    47839 non-null  object
 47  Heating Degree Days        47839 non-null  object
 48  Cooling Degree Days        47839 non-null  object
 49  AQI                        47839 non-null  float64
 50  High AQI                   47839 non-null  float64
 51  PM 1                       47839 non-null  float64
 52  High PM 1                  47839 non-null  int64
 53  PM 2.5                     47839 non-null  float64
 54  High PM 2.5                47839 non-null  int64
 55  PM 10                      47839 non-null  float64
 56  High PM 10                 47839 non-null  int64
 57  Temp .1                    47839 non-null  int64
 58  High Temp .1               47839 non-null  float64
 59  Low Temp                   47839 non-null  float64
 60  Hum .1                     47839 non-null  float64
 61  High Hum .1                47839 non-null  float64
 62  Low Hum .1                 47839 non-null  float64
 63  Dew Point .1               47839 non-null  float64
 64  High Dew Point             47839 non-null  float64
 65  Low Dew Point .1           47839 non-null  float64
 66  Wet Bulb .1                47839 non-null  float64
 67  High Wet Bulb .1           47839 non-null  float64
 68  Low Wet Bulb .1            47839 non-null  float64
 69  Heat Index .1              47839 non-null  float64
 70  High Heat Index            47839 non-null  float64
 71  Unnamed: 71                47839 non-null  float64
dtypes: float64(32), int64(4), object(36)
memory usage: 26.3+ MB

In [6]:
df.columns

Index(['date.time', 'Inside Temp ', 'High Inside Temp ', 'Low Inside Temp ',
       'Inside Hum ', 'High Inside Hum ', 'Low Inside Hum',
       'Inside Dew Point - °C', 'Inside Heat Index', 'Barometer ', 'High Bar ',
       'Low Bar ', 'Absolute Pressure ', 'Temp ', 'High Temp ', 'Low Temp',
       'Hum ', 'High Hum ', 'Low Hum ', 'Dew Point ', 'High Dew Point',
       'Low Dew Point ', 'Wet Bulb ', 'High Wet Bulb ', 'Low Wet Bulb ',
       'Avg Wind Speed ', 'Prevailing Wind Direction', 'High Wind Speed ',
       'High Wind Direction', 'Wind Chill', 'Low Wind Chill ', 'Heat Index ',
       'High Heat Index ', 'THW Index ', 'High THW Index ', 'Low THW Index ',
       'Wind Run ', 'THSW Index', 'High THSW Index ', 'Low THSW Index ',
       'Rain ', 'High Rain Rate ', 'Solar Rad ', 'High Solar Rad ', 'UV Index',
       'High UV Index', 'UV Dose ', 'Heating Degree Days',
       'Cooling Degree Days', 'AQI', 'High AQI', 'PM 1', 'High PM 1 ',
       'PM 2.5 ', 'High PM 2.5 ', 'PM 10 ', 'High PM 10 ', 'Temp .1',
       'High Temp .1', 'Low Temp ', 'Hum .1', 'High Hum .1', 'Low Hum .1',
       'Dew Point .1', 'High Dew Point ', 'Low Dew Point .1', 'Wet Bulb .1',
       'High Wet Bulb .1', 'Low Wet Bulb .1', 'Heat Index .1',
       'High Heat Index', 'Unnamed: 71'],
      dtype='object')

In [7]:
column_details = pd.DataFrame({
        'Column Name': df.columns,
        'Data Type': df.dtypes.values,
        'Memory Usage (KB)': [df[col].memory_usage(deep=True) // 1024 for col in df.columns],
        'Null Values': df.isnull().sum().values,
        'Null Percentage (%)': (df.isnull().sum() / len(df) * 100).round(2).values,
        'Non-Null Values': df.notnull().sum().values,
        'Unique Values': df.nunique().values,
        'Most Frequent Value': [df[col].mode().iloc[0] if not df[col].mode().empty else np.nan for col in df.columns],
        'Min Value': [df[col].min() if np.issubdtype(df[col].dtype, np.number) else np.nan for col in df.columns],
        'Max Value': [df[col].max() if np.issubdtype(df[col].dtype, np.number) else np.nan for col in df.columns]
    })

print(column_details)

          Column Name Data Type  Memory Usage (KB)  Null Values  \
0           date.time    object               2997            0
1        Inside Temp    float64                373            0
2   High Inside Temp    float64                373            0
3    Low Inside Temp    float64                373            0
4         Inside Hum    float64                373            0
..                ...       ...                ...          ...
67   High Wet Bulb .1   float64                373            0
68    Low Wet Bulb .1   float64                373            0
69      Heat Index .1   float64                373            0
70    High Heat Index   float64                373            0
71        Unnamed: 71   float64                373            0

    Null Percentage (%)  Non-Null Values  Unique Values Most Frequent Value  \
0                   0.0            47839          47839    03-01-2024 00:00
1                   0.0            47839            127                28.6
2                   0.0            47839            127                26.6
3                   0.0            47839            127                26.4
4                   0.0            47839            388                61.2
..                  ...              ...            ...                 ...
67                  0.0            47839            135                27.4
68                  0.0            47839            133                27.7
69                  0.0            47839            137                27.3
70                  0.0            47839            318                40.1
71                  0.0            47839            325                33.7

    Min Value  Max Value
0         NaN        NaN
1        21.5       34.1
2        21.6       34.2
3        21.4       34.0
4        39.6       79.9
..        ...        ...
67       16.5       30.5
68       17.1       30.6
69       16.2       30.2
70       20.2       52.9
71       20.3       53.9

[72 rows x 10 columns]

In [10]:
df['date.time'] = pd.to_datetime(df['date.time'], errors='coerce')

df = df.loc[:, ~df.columns.str.contains('Unnamed')]

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = pd.to_numeric(df[col], errors='coerce')

df.dropna(axis=1, how='all', inplace=True)

df.dropna(subset=['date.time'], inplace=True)

In [11]:
df.head()

,date.time,Inside Temp,High Inside Temp,Low Inside Temp,Inside Hum,High Inside Hum,Low Inside Hum,Inside Dew Point - °C,Inside Heat Index,Barometer,...,High Hum .1,Low Hum .1,Dew Point .1,High Dew Point,Low Dew Point .1,Wet Bulb .1,High Wet Bulb .1,Low Wet Bulb .1,Heat Index .1,High Heat Index
0,2024-02-24 10:45:00,23.9,23.9,23.8,60.5,60.5,57.3,15.8,24.3,1019.7,...,57.1,57.1,57.1,18.8,18.8,18.8,20.9,20.9,20.9,29.2
1,2024-02-24 10:50:00,24.2,24.3,24.0,62.7,62.7,60.7,16.6,24.6,1019.6,...,57.1,57.1,57.1,18.8,18.8,18.8,20.9,20.9,20.9,29.2
2,2024-02-24 10:55:00,24.4,24.4,24.2,64.3,64.5,63.4,17.3,25.0,1019.6,...,57.1,57.1,57.1,18.8,18.8,18.8,20.9,20.9,20.9,29.2
3,2024-02-24 11:00:00,24.7,24.7,24.4,64.8,65.0,64.5,17.6,25.3,1019.5,...,60.3,60.4,57.0,18.8,18.9,18.6,20.8,21.0,20.7,28.1
4,2024-02-24 11:05:00,24.9,24.9,24.7,64.9,64.9,64.6,17.8,25.6,1019.5,...,60.3,60.4,57.0,18.8,18.9,18.6,20.8,21.0,20.7,28.1

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28383 entries, 0 to 45662
Data columns (total 69 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date.time              28383 non-null  datetime64[ns]
 1   Inside Temp            28383 non-null  float64
 2   High Inside Temp       28383 non-null  float64
 3   Low Inside Temp        28383 non-null  float64
 4   Inside Hum             28383 non-null  float64
 5   High Inside Hum        28383 non-null  float64
 6   Low Inside Hum         28383 non-null  float64
 7   Inside Dew Point - °C  28383 non-null  float64
 8   Inside Heat Index      28383 non-null  float64
 9   Barometer              28383 non-null  float64
 10  High Bar               28383 non-null  float64
 11  Low Bar                28383 non-null  float64
 12  Absolute Pressure      28383 non-null  float64
 13  Temp                   27124 non-null  float64
 14  High Temp              27124 non-null  float64
 15  Low Temp               27124 non-null  float64
 16  Hum                    27131 non-null  float64
 17  High Hum               27131 non-null  float64
 18  Low Hum                27131 non-null  float64
 19  Dew Point              27094 non-null  float64
 20  High Dew Point         27094 non-null  float64
 21  Low Dew Point          27094 non-null  float64
 22  Wet Bulb               27110 non-null  float64
 23  High Wet Bulb          26993 non-null  float64
 24  Low Wet Bulb           27110 non-null  float64
 25  Avg Wind Speed         27072 non-null  float64
 26  High Wind Speed        27072 non-null  float64
 27  Wind Chill             26926 non-null  float64
 28  Low Wind Chill         26926 non-null  float64
 29  Heat Index             26919 non-null  float64
 30  High Heat Index        26919 non-null  float64
 31  THW Index              26914 non-null  float64
 32  High THW Index         26914 non-null  float64
 33  Low THW Index          26914 non-null  float64
 34  Wind Run               27072 non-null  float64
 35  THSW Index             26874 non-null  float64
 36  High THSW Index        26874 non-null  float64
 37  Low THSW Index         26874 non-null  float64
 38  Rain                   28383 non-null  float64
 39  High Rain Rate         27018 non-null  float64
 40  Solar Rad              27029 non-null  float64
 41  High Solar Rad         27029 non-null  float64
 42  UV Index               2281 non-null   float64
 43  High UV Index          27094 non-null  float64
 44  UV Dose                27094 non-null  float64
 45  Heating Degree Days    27094 non-null  float64
 46  Cooling Degree Days    27124 non-null  float64
 47  AQI                    28383 non-null  float64
 48  High AQI               28383 non-null  float64
 49  PM 1                   28383 non-null  float64
 50  High PM 1              28383 non-null  int64
 51  PM 2.5                 28383 non-null  float64
 52  High PM 2.5            28383 non-null  int64
 53  PM 10                  28383 non-null  float64
 54  High PM 10             28383 non-null  int64
 55  Temp .1                28383 non-null  int64
 56  High Temp .1           28383 non-null  float64
 57  Low Temp               28383 non-null  float64
 58  Hum .1                 28383 non-null  float64
 59  High Hum .1            28383 non-null  float64
 60  Low Hum .1             28383 non-null  float64
 61  Dew Point .1           28383 non-null  float64
 62  High Dew Point         28383 non-null  float64
 63  Low Dew Point .1       28383 non-null  float64
 64  Wet Bulb .1            28383 non-null  float64
 65  High Wet Bulb .1       28383 non-null  float64
 66  Low Wet Bulb .1        28383 non-null  float64
 67  Heat Index .1          28383 non-null  float64
 68  High Heat Index        28383 non-null  float64
dtypes: datetime64[ns](1), float64(64), int64(4)
memory usage: 15.2 MB

In [14]:
print(df.columns.tolist())

['date.time', 'Inside Temp ', 'High Inside Temp ', 'Low Inside Temp ', 'Inside Hum ', 'High Inside Hum ', 'Low Inside Hum', 'Inside Dew Point - °C', 'Inside Heat Index', 'Barometer ', 'High Bar ', 'Low Bar ', 'Absolute Pressure ', 'Temp ', 'High Temp ', 'Low Temp', 'Hum ', 'High Hum ', 'Low Hum ', 'Dew Point ', 'High Dew Point', 'Low Dew Point ', 'Wet Bulb ', 'High Wet Bulb ', 'Low Wet Bulb ', 'Avg Wind Speed ', 'High Wind Speed ', 'Wind Chill', 'Low Wind Chill ', 'Heat Index ', 'High Heat Index ', 'THW Index ', 'High THW Index ', 'Low THW Index ', 'Wind Run ', 'THSW Index', 'High THSW Index ', 'Low THSW Index ', 'Rain ', 'High Rain Rate ', 'Solar Rad ', 'High Solar Rad ', 'UV Index', 'High UV Index', 'UV Dose ', 'Heating Degree Days', 'Cooling Degree Days', 'AQI', 'High AQI', 'PM 1', 'High PM 1 ', 'PM 2.5 ', 'High PM 2.5 ', 'PM 10 ', 'High PM 10 ', 'Temp .1', 'High Temp .1', 'Low Temp ', 'Hum .1', 'High Hum .1', 'Low Hum .1', 'Dew Point .1', 'High Dew Point ', 'Low Dew Point .1', 'Wet Bulb .1', 'High Wet Bulb .1', 'Low Wet Bulb .1', 'Heat Index .1', 'High Heat Index']

In [15]:
df.columns = df.columns.str.strip()

temperature_col = next((col for col in df.columns if "Temp" in col and "High" not in col and "Low" not in col), None)
humidity_col = next((col for col in df.columns if "Hum" in col and "High" not in col and "Low" not in col), None)
pressure_col = next((col for col in df.columns if "Barometer" in col or "Pressure" in col), None)

print(f"Temperature Column: {temperature_col}")
print(f"Humidity Column: {humidity_col}")
print(f"Pressure Column: {pressure_col}")

Temperature Column: Inside Temp
Humidity Column: Inside Hum
Pressure Column: Barometer